# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
        ('carpool', '0003_auto_20160928_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='wall',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='wall.Wall'),
            preserve_default=False,
        ),
    ]
