# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0004_carpool_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpool',
            name='max_extra_distance',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
