# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carpool_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
