# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160929_1620'),
    ]

    operations = [
    ]
