# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160928_1823'),
        ('account', '0004_auto_20160928_1839'),
    ]

    operations = [
    ]
