# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20160929_0155'),
        ('account', '0005_merge_20160929_0750'),
    ]

    operations = [
    ]
