# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20160929_1813'),
        ('wall', '0002_auto_20160929_1840'),
    ]

    operations = [
    ]
